### ISSUE TITLE
Release for Elm 0.19

### ISSUE THREAD

**Issue by michaeljones** [hecrj/elm-slug#1]
Hey, we're happy users of your library and we're looking to update to Elm 0.19. I see you have a branch for the alpha & beta. Do you know if there is more work to be done for a final release? I would be happy to help if I can?

Thanks for the library!

**Comment by hecrj** [comment]
I just released `1.0.2` for Elm 0.19!

I was waiting to port the tests, which is blocked by this issue: https://github.com/elm-explorations/test/issues/15

I decided to release anyways and fix the tests when possible: https://github.com/hecrj/elm-slug/issues/2

**Comment by michaeljones** [comment]
Thank you! Much appreciated. I'm still learning which bits of the ecosystem are catching up with Elm 0.19. I guess I hoped everything would magically be in place already :)
